#!/bin/bash
# This file is part of TbSync.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# $1 link to base web server       : https://tbsync.jobisoft.de/beta
# $2 local path of base web server : /var/www/jobisoft.de/tbsync/beta
# $3 name of XPI                   : TbSync.xpi
# $4 name of update.rdf            : update-dav.rdf

git clean -df
git checkout -- .
git pull

version=$(cat manifest.json | jq -r .version)

sed -i "s/%VERSION%/$version/g" "beta-release-channel-update.rdf"
sed -i "s|%LINK%|$1/$3|g" "beta-release-channel-update.rdf"

 echo "Releasing version $version via beta release channel (will include updateURL)"
 sed -i "s|\"name\": \"TbSync\",|\"name\": \"TbSync [Beta Release Channel]\",\n  \"update_url\": \"$1/$4\",|g" "manifest.json"

cp beta-release-channel-update.rdf $2/$4

rm $3
zip -r $3 content _locales skin chrome.manifest manifest.json bootstrap.js LICENSE CONTRIBUTORS.md
cp $3 $2/$3
