pref("extensions.tzpush.host", "");
pref("extensions.tzpush.user", "");
pref("extensions.tzpush.deviceId", "");
pref("extensions.tzpush.synckey", "");
pref("extensions.tzpush.folderID", "");
pref("extensions.tzpush.LastSyncTime", "0");
pref("extensions.tzpush.https",false);
pref("extensions.tzpush.abname","moz-abmdbdirectory://abook.mab");
pref("extensions.tzpush.polkey","0");
pref("extensions.tzpush.prov",false);
pref("extensions.tzpush.folderSynckey","");
pref("extensions.tzpush.autosync",0);
pref("extensions.tzpush.go","0");
pref("extensions.tzpush.birthday",false);
pref("extensions.tzpush.debugwbxml","0");
pref("extensions.tzpush.seperator",", ");
pref("extensions.tzpush.maxnumbertosend","50");
pref("extensions.tzpush.displayoverride",false);
pref("extensions.tzpush.asversion","14");
pref("extensions.tzpush.showanniversary",true);
pref("extensions.tzpush.hidephones",false);
pref("extensions.tzpush.downloadonly",false);
